name: CI - Ejecutar Pruebas Automáticas

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17' 

    - name: Compilar el proyecto
      run: javac suma.java 

    - name: Ejecutar pruebas
      run: java suma 